
== Environments

An important mechanism for customization is the idea of an _environment_.
Environments are usually associated with receivers and the framework looks up
values in the environment by using an overloaded `query` function. In particular, the
framework calls `R::query(get_env_t)` to find the environment of a receiver type
`R`, and `E::query(get_stop_token_t)` to find the stop token of an environment
type E. `async::get_env_t` and `async::get_stop_token_t` are the tag types used for this
purpose.

In practice, here's what supporting that might look like for a custom receiver
that supports cancellation:

[source,cpp]
----
struct custom_receiver {
  auto set_value(auto&&...) { ... }
  auto set_error(auto&&) { ... }
  auto set_stopped() { ... }

  [[nodiscard]] constexpr auto query(async::get_env_t) const {
    return async::prop{async::get_stop_token_t{}, stop_source->get_token()};
  }

  inplace_stop_source* stop_source;
};
----

Given this, we can construct an arbitrary composition of senders with this as
the final receiver. If we want to cancel the operation, we call `request_stop()`
on the (external) `inplace_stop_source`. The internal senders, receivers and
operation states in the composition can observe this request by querying the
stop token in the environment for the final receiver, and this knowledge can
propagate through the sender-receiver chain.

NOTE: Remember that a receiver should not own a stop_source: receivers must
be movable, and in general a stop_source is not.

=== Constructing and composing environments

An environment is conceptually a key-value store through which a receiver (or a
sender) provides properties to algorithms (sender adaptors) to customize the way
they work.

Some of the facilities for environment handling are covered in https://wg21.link/p3325[P3325].

A `prop` is a single key-value pair. Construct one with a query and the value
that will be returned for that query.

[source,cpp]
----
auto e = async::prop{async::get_stop_token_t{}, stop_source->get_token()};
----

NOTE: A `prop` _is_ an environment. A small one, but it models the
concepts required.

`env` is how we compose multiple properties, or multiple environments:

[source,cpp]
----
auto e = async::env{
           async::prop{async::get_stop_token_t{}, stop_source->get_token()},
           async::prop{async::get_allocator_t{}, async::stack_allocator{}}};
----

This allows us to use an existing environment and extend it with new properties,
or override existing ones.

[source,cpp]
----
auto old_e = /* existing environment */;
auto e = async::env{
           async::prop{async::get_stop_token_t{}, stop_source->get_token()},
           old_e};
----

In this case, whether or not `get_stop_token` is a valid query on `old_e`,
calling it on `e` will return the newly-provided stop token.
