
== Sender factories

=== `just`

Found in the header: `async/just.hpp`

`just` returns a sender that produces the provided values.

[source,cpp]
----
auto sndr = async::just(42, 17);
// sndr produces (sends) the values 42 and 17
----

`just` can be given a name that is used for debug events. By default, its name
is `"just"`.

[source,cpp]
----
auto sndr = async::just<"the answer">(42);
----

[NOTE]
.For functional programmers
====
`just` is equivalent to `pure` or `return`: lifting a value into the
continuation monad.
====

=== `just_error`

Found in the header: `async/just.hpp`

`just_error` is like `just`, but instead of completing by calling `set_value` on
a receiver, it will call `set_error`.

[source,cpp]
----
auto sndr = async::just_error(42);
// sndr produces (sends) the value 42 on the error channel
----

`just_error` can be given a name that is used for debug events. By default, its name
is `"just_error"`.

[source,cpp]
----
auto sndr = async::just_error<"oops">(42);
----

NOTE: Unlike the value channel, only one value is normally sent on the error channel.

=== `just_error_result_of`

Found in the header: `async/just_result_of.hpp`

`just_error_result_of` is like `just_error`, but instead of taking raw values, it takes
functions that produce values.

[source,cpp]
----
auto sndr1 = async::just_error_result_of([] { return 42; });
// sndr1 sends 42 on the error channel

auto sndr2 = async::just_error_result_of([] { return 42; },
                                         [] { do_something(); });
// sndr2 also sends 42 on the error channel,
// as well as executing do_something() - which returns void
----

`just_error_result_of` can be given a name that is used for debug events. By default, its name
is `"just_error_result_of"`.

[source,cpp]
----
auto sndr = async::just_error_result_of<"oops">([] { return 42; });
----

NOTE: Do not rely on the order of evaluation of the functions given to
`just_error_result_of`!

NOTE: Only one value is normally sent on the error channel. So exactly one of
the functions passed to `just_error_result_of` should return something other than
`void`.

=== `just_result_of`

Found in the header: `async/just_result_of.hpp`

`just_result_of` is like `just`, but instead of taking raw values, it takes
functions that produce values.

[source,cpp]
----
auto sndr1 = async::just_result_of([] { return 42; },
                                   [] { return 17; });
// sndr1 produces (sends) the values 42 and 17

auto sndr2 = async::just_result_of([] { return 42; },
                                   [] { do_something(); },
                                   [] { return 17; });
// sndr2 also produces (sends) the values 42 and 17,
// as well as executing do_something() - which returns void
----

`just_result_of` can be given a name that is used for debug events. By default, its name
is `"just_result_of"`.

[source,cpp]
----
auto sndr = async::just_result_of<"the answer">([] { return 42; });
----

NOTE: Do not rely on the order of evaluation of the functions given to
`just_result_of`!

`just_result_of` behaves the same way as `just` followed by `then`:

[source,cpp]
----
auto s = async::just_result_of([] { return 42; });

// as if:
auto s = async::just() | async::then([] { return 42; });
----

=== `just_stopped`

Found in the header: `async/just.hpp`

`just_stopped` is like `just`, but instead of completing by calling `set_value` on
a receiver, it will call `set_stopped`.

[source,cpp]
----
auto sndr = async::just_stopped();
// sndr completes on the stopped channel
----

`just_stopped` can be given a name that is used for debug events. By default, its name
is `"just_stopped"`.

[source,cpp]
----
auto sndr = async::just_stopped<"cancel">();
----

=== `read_env`

Found in the header: `async/read_env.hpp`

`read_env` takes a _query_ and returns a sender that sends the value denoted by
that query, obtained from the environment of the receiver the sender is
connected to.

[source,cpp]
----
auto s = async::read_env(async::get_stop_token);
// when connected to a receiver, s will send the stop token from that receiver's environment
----

`read_env` can be given a name that is used for debug
events. By default, the name is the name exposed by the query, or if there is no
such name, `"read_env"`.

[source,cpp]
----
auto s1 = async::read_env<"gst">(async::get_stop_token); // name = "gst"
auto s2 = async::read_env(async::get_stop_token);        // name = "get_stop_token"
auto s3 = async::read_env(unnamed_query{});              // name = "read_env"
----

=== `schedule`

See xref:schedulers.adoc#_schedulers_2[`Schedulers`].

A _scheduler_'s `schedule` function returns a sender that produces nothing, but
represents running on that scheduler's compute resource. We can chain more work
(i.e. other senders) on to that starting point.

[source,cpp]
----
// s is a scheduler
auto sndr = s.schedule();
// sndr does no work (yet) but when consumed, will run according to that
// scheduler. We can use sender adaptors to compose more work.
----
