
== Sender consumers

=== `start_detached`

Found in the header: `async/start_detached.hpp`

`start_detached` is synonymous with
xref:sender_consumers.adoc#_start_detached_unstoppable[`start_detached_unstoppable`].

=== `start_detached_stoppable`

Found in the header: `async/start_detached.hpp`

`start_detached_stoppable` takes a sender, connects and starts it, and returns, leaving
the work running detached. The return value is a
https://intel.github.io/cpp-std-extensions/#_optional_hpp[`stdx::optional`]. If
the optional is empty, the sender was not started. Otherwise, it contains a
pointer to an xref:cancellation.adoc#_cancellation[`inplace_stop_source`] that
can be used to cancel the operation.

[source,cpp]
----
auto sndr = async::just(42);
auto started = async::start_detached_stoppable(sndr);
// in this case, starting the sender also completes it
----

If a sender starts detached, its operation state has to be allocated somewhere.
That is achieved through an xref:attributes.adoc#_allocator[allocator]
determined from the sender's attributes. Without further customization, if a
sender completes synchronously, it will use the `stack_allocator` by default.
Otherwise it will use the `static_allocator`.

To hook into the static xref:attributes.adoc#_allocator[allocation strategy], a
template argument (representing the name of the allocation domain) can be given
to `start_detached_stoppable`. This is used to select a static allocator.

[source,cpp]
----
auto result = async::start_detached_stoppable<struct Name>(s);
----

The default template argument results in a different `static_allocator` for each
call site, with a default allocation limit of 1. If a name is given, that name
is used to specialize the `static_allocator`, and can be used with
xref:sender_consumers.adoc#_stop_detached[`stop_detached`] to request
cancellation.

If the allocator's `construct` method returns `false` (presumably because the
allocation limit has been reached), the result of `start_detached_stoppable` is an empty
optional.

An extra xref:environments.adoc#_environments[environment] may be given to
`start_detached_stoppable` in order to control sender behaviour, or to specify a custom
allocator:

[source,cpp]
----
auto result = async::start_detached_stoppable(
    s, async::prop{async::get_allocator_t{}, custom_allocator{}}));
----

=== `start_detached_unstoppable`

Found in the header: `async/start_detached.hpp`

`start_detached_unstoppable` behaves identically to `start_detached_stoppable`, except
that the returned optional value contains a pointer to a `never_stop_source`,
which has the same interface as an
xref:cancellation.adoc#_cancellation[`inplace_stop_source`] but never actually
cancels the operation. So `start_detached_unstoppable` is slightly more
efficient than `start_detached` for the cases where cancellation is not
required.

[source,cpp]
----
auto result = async::start_detached_unstoppable<struct Name>(s);
----

=== `stop_detached`

Found in the header: `async/start_detached.hpp`

A sender started with `start_detached` may be cancelled with `stop_detached`,
using the same template argument:

[source,cpp]
----
struct Name;
auto result = async::start_detached<Name>(s);

// later, in another context...
auto stop_requested = async::stop_detached<Name>(); // true if a stop was requested
----

`stop_detached` will return `false` if it cannot request a stop:

* because no sender with that name was given to `start_detached`
* because the sender has already completed
* because a stop was already requested
* because the sender was started using `start_detached_unstoppable`
* because the associated allocator supports multiple operation states, so a
  single template argument is not sufficient to determine which one to stop (in
  this case, the return value of `start_detached` may be used to request
  cancellation)

=== `sync_wait`

`sync_wait` is synonymous with
xref:sender_consumers.adoc#_sync_wait_static[`sync_wait_static`].

=== `sync_wait_dynamic`

Found in the header: `async/sync_wait.hpp`

`sync_wait_dynamic` takes a sender and:

. connects and starts it
. blocks waiting for it to complete
. returns any values it sends in a `std::optional<stdx::tuple<...>>`

[source,cpp]
----
auto sndr = async::just(42);
auto [i] = async::sync_wait_dynamic(sndr).value();
// i is now 42
----

As with xref:sender_consumers.adoc#_start_detached[`start_detached`], an extra xref:environments.adoc#_environments[environment] may be given to
`sync_wait_dynamic` in order to control sender behaviour:

[source,cpp]
----
auto result = async::sync_wait_dynamic(
    s, async::prop{async::get_custom_property_t{}, custom_property{}}));
----

`sync_wait_dynamic` provides a xref:schedulers.adoc#_runloop_scheduler[`runloop_scheduler`] that can be read from the
environment, so that a sender may append further work:
[source,cpp]
----
auto s = async::get_scheduler()
       | async::let_value([&](auto sched) {
           return async::start_on(sched, async::just(42));
       });
auto result = s | async::sync_wait_dynamic();
----

=== `sync_wait_static`

Found in the header: `async/sync_wait.hpp`

`sync_wait_static` behaves like `sync_wait_dynamic`, except that it does not
provide a xref:schedulers.adoc#_runloop_scheduler[`runloop_scheduler`], so further work cannot be appended.

=== `trivially_sync_waitable`

Found in the header: `async/sync_wait.hpp`

A concept that is true when a sender can be passed to
xref:sender_consumers.adoc#_sync_wait_static[`sync_wait_static`] (given an
appropriate environment, if necessary) and will complete synchronously.

[source,cpp]
----
auto sndr = async::just(42);
static_assert(async::trivially_sync_waitable<decltype(sndr)>);
----

NOTE: `trivially_sync_waitable` can be given a second argument which is the
environment type that would be passed to `sync_wait_static`.
