
== Sender adaptors

=== `continue_on`

Found in the header: `async/continue_on.hpp`

`continue_on` allows an asynchronous computation to switch where it is running.

[source,cpp]
----
// s1 and s2 are different schedulers representing different computation contexts
auto sndr = async::start_on(s1, async::just(42));
auto t = async::continue_on(sndr, s2);
auto transferred = async::then(t, [] (int i) { return std::to_string(i); });
// when transferred runs:
// first on s1 it will produce 42
// then on s2 it will convert 42 to a string, producing "42"
----

WARNING: If the upstream sender _causes_ the downstream scheduler to run, using
`continue_on` is incorrect: xref:sender_adaptors.adoc#_incite_on[`incite_on`]
should be used instead.

=== `incite_on`

Found in the header: `async/incite_on.hpp`

`incite_on` is like xref:sender_adaptors.adoc#_continue_on[`continue_on`] but is
for the use case where running a sender causes a scheduler to be triggered. It
is intended for use with xref:schedulers.adoc#_trigger_scheduler[`trigger_scheduler`].

[source,cpp]
----
auto sndr = async::just([] { send_request(); })
          | async::incite_on(trigger_scheduler<"msg">{})
          | async::then([] (auto msg) { /* handle response */ });

auto on_recv_message(auto msg) {
  async::run_triggers<"msg">(msg);
}

// when sndr runs:
// send_message will send a request
// time passes...
// when the response is received, its handler calls run_triggers
// sndr continues on the trigger scheduler
----

The sender upstream of `incite_on` must complete by sending a function. When
that function is called it will in some way cause the downstream scheduled
sender to run. This may happen indirectly (e.g. as above, via another
asynchronous mechanism like message reception), or directly. The upstream sender
must complete successfully in one way -- with this function -- although it may
still send an error, or be cancelled.

`continue_on` would be incorrect in this circumstance, because once the `just`
completes and sends a message, `continue_on(trigger_scheduler{})` is racing with
message reception. If the message is received before the `trigger_scheduler` is
ready to fire, the trigger would be missed.

NOTE: The incited scheduler must produce a sender which completes
asynchronously. A synchronous scheduler would require no incitement, and
`continue_on` would be correct.

=== `incite_on_any`

Found in the header: `async/incite_on.hpp`

Sometimes it's useful to run a function which might incite any of a number of
trigger schedulers. That's what `incite_on_any` is for.

[source,cpp]
----
auto sndr = async::just([] { send_request(); })
          | async::incite_on_any(trigger_scheduler<"msg0", msg0_t>{},
                                 trigger_scheduler<"msg1", msg1_t>{},
                                 trigger_scheduler<"msg2", msg2_t>{})
          | async::then(stdx::overload{
                            [] (msg0_t msg) { /* handle msg */ },
                            [] (msg1_t msg) { /* handle msg */ },
                            [] (msg2_t msg) { /* handle msg */ }
                        });

auto on_recv_message(auto msg) {
  switch (msg_type(msg)) {
    case MSG_0:
      async::run_triggers<"msg0">(to<msg0_t>(msg)); break;
    case MSG_1:
      async::run_triggers<"msg1">(to<msg1_t>(msg)); break;
    case MSG_2:
      async::run_triggers<"msg2">(to<msg2_t>(msg)); break;
  }
}
----

=== `into_variant`

Found in the header: `async/into_variant.hpp`

`into_variant` adapts a sender that has several possible value completions into
a sender with a single value completion that is a variant of tuples, where each
tuple represents one of the original sender's value completions.

[source,cpp]
----
auto sndr = async::make_variant_sender(
                selection,
                [] { return async::just(42, 17); },
                [] { return async::just(2.718f, 3.14f); })
          | async::into_variant();

// sndr will complete with set_value(variant<tuple<int, int>, tuple<float, float>>)
----

NOTE: Some sender consumers (like
xref:sender_consumers.adoc#_sync_wait[`sync_wait`]) require the sender to have
one possible value completion.

=== `let_error`

Found in the header: `async/let_error.hpp`

`let_error` is like xref:_let_value[`let_value`], but instead of applying the
function to values, it applies to errors.

[source,cpp]
----
auto sndr = async::just_error(42);
auto let_sndr = async::let_error(sndr, [] (int i) { return async::just(std::to_string(i)); });
// when run, let_sndr will produce the string "42"
----

=== `let_stopped`

Found in the header: `async/let_stopped.hpp`

`let_stopped` is like xref:_let_value[`let_value`], but instead of applying the
function to values, it applies to the stopped channel.

[source,cpp]
----
auto sndr = async::just_stopped();
auto let_sndr = async::let_stopped(sndr, [] { return async::just(42); });
// when run, let_sndr will produce 42
----

=== `let_value`

Found in the header: `async/let_value.hpp`

`let_value` is like xref:_then[`then`], but the function given to it will itself
return a sender.

[source,cpp]
----
auto sndr = async::just(42);
auto let_sndr = async::let_value(sndr, [] (int i) { return async::just(std::to_string(i)); });
// when run, let_sndr will produce the string "42"
----

[NOTE]
.For functional programmers
====
`let_value` is equivalent to monadic bind.
====

A primary use case of `let_value` is to allow dynamic selection of senders at
runtime based on what a previous sender produced. In this case, the function
passed to `let_value` must return a single type. A naive approach doesn't work:

[source,cpp]
----
auto sndr = async::just(42);
auto let_sndr = async::let_value(
    sndr,
    [] (int i) {
      if (i == 42) {
        return async::just(std::to_string(i));
      } else {
        return async::just_error(i);
      }
    });
// this fails to compile because the lambda tries to return either a just sender
// or a just_error: these are different types
----

For this use case, the function provided to `let_value` must return a
xref:variant_senders.adoc#_variant_senders[variant sender] : a sender that can
encapsulate several others and select which one is used at runtime.

[source,cpp]
----
auto sndr = async::just(42);
auto let_sndr = async::let_value(
    sndr,
    [] (int i) {
      return async::make_variant_sender(
        i == 42,
        [=] { return async::just(std::to_string(i)); },
        [=] { return async::just_error(i); }
      );
    });
----

This works: using the helper function `make_variant_sender`, `let_value` can
successfully make a runtime choice about which sender to proceed with.

=== `periodic`

Found in the header: `async/periodic.hpp`

`periodic` takes a sender and repeats it indefinitely according to the given
time period. When the sender completes with a value, it is reconnected and
restarted (rescheduled). A `periodic` sender will not complete on the value
channel, but can still be stopped, or complete with an error.

[source,cpp]
----
auto s = time_scheduler{}.sender() | ... ;
auto p = s | async::periodic(1s);
// when p runs, s is scheduled for 1 second in the future. If s sends an error
// or is stopped, p reflects that. If s completes successfully, the result is
// discarded and s runs again, another second in the future.
----

NOTE: `periodic` works hand-in-glove (and only) with a
xref:schedulers.adoc#_time_scheduler[`time_scheduler`] sender that is not given
a duration.

IMPORTANT: To avoid drift, `periodic` reschedules itself based not on the
current time, but on its expiration time. However the periodic invariant breaks
down if a task takes longer to complete than its period (which may happen if
tasks can spike in the time taken to execute them). In that case, by default,
`periodic` will reschedule immediately - but this behaviour can be
parameterized.

[source,cpp]
----
auto s = time_scheduler{}.sender() | ... ;

// safe_immediate_expiry is the default behaviour: if the sender exceeds 1s, so
// that its next execution time would occur in the past, then instead it will be
// rescheduled immediately.
auto p1 = s | async::periodic<"name", async::safe_immediate_expiry>(1s);

// safe_quantized_expiry means that if the sender's next execution time would
// occur in the past, instead it will be rescheduled for the next time its
// "tick" would occur. i.e. one or more "ticks" will be skipped.
auto p2 = s | async::periodic<"name", async::safe_quantized_expiry>(1s);

// unsafe_expiry means that no checks happen: if the sender's next execution
// time occurs in the past, so be it. This is unsafe since it has the potential
// to cause a growing backlog.
auto p3 = s | async::periodic<"name", async::unsafe_expiry>(1s);
----

The `"name"` given to the `periodic` adaptor here will show up in
xref:debug.adoc#_naming_senders_and_operations[debug output].

=== `periodic_n`

Found in the header: `async/periodic.hpp`

`periodic_n` works the same way as `periodic`, but repeats a given number of times.

[source,cpp]
----
auto s = time_scheduler{}.sender() | ... ;
auto p = s | async::periodic_n(1s, 5);
// p repeats s 5 times
----

NOTE: `periodic_n` must always run at least once to be able to complete. So
`periodic_n(1s, 1)` repeats once, i.e. runs twice. `periodic_n(1s, 0)` runs once
(thus is equivalent to instead starting the sender chain with
`time_scheduler{1s}.sender()`).

=== `periodic_until`

Found in the header: `async/periodic.hpp`

`periodic_until` works the same way as `periodic`, but repeats the sender until a
given predicate returns true.

[source,cpp]
----
auto s = time_scheduler{}.sender() | ... ;
auto p = s | async::periodic_until(1s, [] (auto&&...) { return true; });
----

NOTE: The arguments passed to the predicate are those in the value completion(s)
of the sender.

NOTE: `periodic` never completes other than by error or cancellation, but
`periodic_n` and `periodic_until` both complete successfully with the same
completion as the adapted sender.

=== `repeat`

Found in the header: `async/repeat.hpp`

`repeat` takes a sender and repeats it indefinitely. When the sender completes
with a value, it is reconnected and restarted. This is useful for tasks that
should repeat immediately on finishing. A `repeat` sender can still be stopped,
or complete with an error.

[source,cpp]
----
auto s = some_sender | async::repeat();
// when s runs, some_sender runs. If some_sender sends an error or is stopped, s
// reflects that. If some_sender completes successfully, the result is discarded
// and some_sender runs again.
----

NOTE: The difference between `periodic` and `repeat` is that `periodic`
interacts with the `time_scheduler` to eliminate any drift caused by
bookkeeping. `repeat` of a periodic task may exhibit drift. `periodic` must work
with a `time_scheduler` sender; `repeat` can work with any sender.

`repeat` can also be given a "loop function". This is a synchronous function
that runs _after_ the repeated sender each time "around the loop". This is
useful for situations where the execution of the sender depends on some other
stimulus, and it avoids a race condition in the same way that
xref:sender_adaptors.adoc#_incite_on[`incite_on`] does.

[source,cpp]
----
auto s = trigger_scheduler<"recv response", Rsp>{}.schedule()
       | then([] (Rsp r) { /* handle response */ })
       | async::repeat([] { /* send another request */ );
start_detached(s);

// At this point, s is waiting for a response (which will incite the trigger).
// When we send a request (including the first one), a response may come immediately.

send_first_request();

// s will handle the response, then send another request, repeating until cancelled.
// It is important that s be ready to receive a response BEFORE each request is sent.
// Otherwise (in a race avoided by this construction) it may miss the response to its request.
----

The loop function arguments (if any) are what the repeated sender sends.

NOTE: The "loop function" given to `repeat` will not be run on (before) the "first
iteration" of the loop. Nor will it be run after cancellation.

=== `repeat_n`

Found in the header: `async/repeat.hpp`

`repeat_n` works the same way as `repeat`, but repeats a given number of times.

NOTE: `repeat_n` must always run at least once to be able to complete. So
`repeat_n(1)` repeats once, i.e. runs twice. `repeat_n(0)` runs once (thus is redundant).

=== `repeat_until`

Found in the header: `async/repeat.hpp`

`repeat_until` works the same way as `repeat`, but repeats the sender until a
given predicate returns true.

[source,cpp]
----
// this is the same as repeat_n(0), i.e. just run once
auto s = some_sender | async::repeat_until([] (auto&&...) { return true; });
----

NOTE: The arguments passed to the predicate are those in the value completion(s)
of the sender.

NOTE: `repeat` never completes other than by error or cancellation, but
`repeat_n` and `repeat_until` both complete successfully with the same
completion as the adapted sender.

=== `retry`

Found in the header: `async/retry.hpp`

`retry` takes a multishot sender and wraps it: if that sender sends an error,
the error gets discarded and the sender is reconnected and restarted.

[source,cpp]
----
auto s = some_sender | async::retry();
// if some_sender sends an error, it will be reconnected and restarted
// s completes when some_sender completes with set_value or set_stopped
----

CAUTION: `retry` can cause stack overflows if used with a scheduler that
doesn't break the callstack, like
xref:schedulers.adoc#_inline_scheduler[`inline_scheduler`].

=== `retry_until`

Found in the header: `async/retry.hpp`

`retry_until` works like `retry`, but takes a predicate. If the predicate
returns true, `retry_until` can complete on the error channel.

[source,cpp]
----
// this is the same as just running the sender
auto s = some_sender | async::retry_until([] (auto&&) { return true; });
----

NOTE: The arguments passed to the predicate are those in the error completion(s)
of the sender.

=== `sequence`

Found in the header: `async/sequence.hpp`

`sequence` is like xref:_let_value[`let_value`], but it must take a nullary
function that returns a sender. In other words, the first sender's values (if
any) are discarded before the second sender is run.

[source,cpp]
----
auto sndr = async::just(17);
auto seq_sndr = async::sequence(sndr, [] { return async::just(42); });
// when run, seq_sndr will produce 42
----

[NOTE]
.For functional programmers
====
`sequence` is equivalent to `(>>)` in Haskell.
====

`let_value` should be used when dynamic sender selection at runtime is required
based on a sent value. When it suffices to run one sender after another with no
dependency between them, use `sequence`. Because `sequence` is more constrained,
in some cases it allows more compile-time manipulation like
xref:attributes.adoc#_sender_attributes[sender attribute interrogation].

Sequencing unrelated senders is common enough that there is a shortcut for
`sequence` that saves typing a lambda expression: `seq`.

[source,cpp]
----
auto seq_sndr = async::just(17) | async::seq(async::just(42));
// when run, seq_sndr will produce 42
----

`seq` is useful, but notice the difference between these two:

[source,cpp]
----
auto seq1 = async::seq(async::just(move_only_obj{}));
auto seq2 = async::sequence([] { return async::just(move_only_obj{}); });
----

They are compositionally the same. However `seq1` constructs the sender (`just`)
early; `seq2` constructs the sender only when called. In this case with a
move-only object, that means that `seq1` is single shot, but `seq2` is
multishot.

=== `split`

Found in the header: `async/split.hpp`

Some senders are single shot: they can only run once. Doing so may consume
resources that the sender owns. The call to `connect` such a sender has an
overload for rvalue references only.

Other senders are multishot and can connect to multiple receivers and run
multiple times.

`split` turns a single shot sender into a multishot sender. It has no effect
when called on a multishot sender.

=== `start_on`

Found in the header: `async/start_on.hpp`

`start_on` takes a scheduler and a sender, and composes them so that the work
will run on that scheduler. It chains the sender work onto the result of
calling `schedule`.

[source,cpp]
----
// s is a scheduler
auto sndr = async::start_on(s, async::just(42));
// when run, sndr will execute on the compute resource specified by s, producing 42
----

`start_on` is equivalent to `seq(scheduler.schedule(), sender`):
[source,cpp]
----
auto sndr = s.schedule() | async::seq(async::just(42));
----

=== `then`

Found in the header: `async/then.hpp`

`then` takes a sender and a function, and returns a sender that will call the
function with the values that the sender sends.
[source,cpp]
----
auto sndr = async::just(42);
auto then_sndr = async::then(sndr, [] (int i) { return std::to_string(i); });
// when run, then_sndr will produce the string "42"
----

[NOTE]
.For functional programmers
====
`then` is equivalent to `fmap`.
====

`then` can also take a variadic pack of functions, for a use case when the
sender sends multiple values. This provides an easy way to apply a different
function to each value, and avoids having to return a tuple of values which
would then require extra handling downstream.
[source,cpp]
----
auto sndr = async::just(42, 17);
auto then_sndr = async::then(sndr,
    [] (int i) { return std::to_string(i); },
    [] (int j) { return j + 1; });
// when run, then_sndr will send "42" and 18
----

In both the "normal" and variadic cases, functions passed to `then` may return
`void`. In the "normal" case, the resulting `then` sender completes by calling
`set_value` with no arguments. In the variadic case, `set_value` will be called
with the `void`-returns filtered out.
[source,cpp]
----
auto s1 = async::just(42);
auto normal_then = async::then(s1, [] (int) {});
// when run, this will call set_value() on the downstream receiver

auto s2 = async::just(42, 17);
auto variadic_then = async::then(s2,
    [] (int i) { return std::to_string(i); },
    [] (int) {});
// when run, this will call set_value("42") on the downstream receiver
----

In the variadic case, `then` can distribute the values sent from upstream to the
functions by arity:

[source,cpp]
----
auto s = async::just(42, 17, false, "Hello"sv);
auto t = async::then(s,
    [] (int i, int j) { return i + j; },
    [] (auto b, std::string_view s) -> std::string_view { if (b) return s; else return "no"; },
    [] { return 1.0f; });
// when run, this will call set_value(59, "no", 1.0f) on the downstream receiver
----

=== `then_each`

Found in the header: `async/then_each.hpp`

`then_each` takes a sender and several functions, and returns a sender that will call
each of the functions with the values that the sender sends.

[source,cpp]
----
auto sndr = async::just(42);
auto then_each_sndr = async::then_each(sndr,
    [] (int i) { return std::to_string(i); },
    [] (int i) { return i + 1; });
// when run, then_each_sndr will produce values "42" and 43
----

=== `timeout_after`

Found in the header: `async/timeout_after.hpp`

`timeout_after` takes a sender, a duration and an error value, and returns a
sender that will complete with an error after the given timeout. Otherwise it
will complete as the given sender completes.

[source,cpp]
----
auto sndr = async::start_on(my_scheduler{}, async::just(42))
          | async::timeout_after(1s, error{17});
// when run, sndr will produce 42 on the value channel if my_scheduler runs within 1s
// otherwise it will produce error{17} on the error channel
----

NOTE: `timeout_after` is implemented using xref:_when_any[`stop_when`].

=== `transform_error`

Found in the header: `async/then.hpp`

`transform_error` works like `then`, but instead of applying the function to values, it applies to errors.

[source,cpp]
----
auto sndr = async::just_error(42);
auto te_sndr = async::transform_error(sndr, [] (int i) { return std::to_string(i); });
// when run, te_sndr will produce the string "42" on the error channel
----

NOTE: Like `then`, `transform_error` can distribute the sent values to the
functions by arity. However, only one value is normally sent on the error channel.

=== `upon_error`

Found in the header: `async/then.hpp`

`upon_error` works like `then`, but instead of applying the function to values, it applies to errors.

[source,cpp]
----
auto sndr = async::just_error(42);
auto ue_sndr = async::upon_error(sndr, [] (int i) { return std::to_string(i); });
// when run, ue_sndr will produce the string "42" on the value channel
----

NOTE: The difference between `transform_error` and `upon_error` is that
`transform_error` completes on the error channel, and `upon_error` completes on
the value channel.

=== `upon_stopped`

Found in the header: `async/then.hpp`

`upon_stopped` works like `then`, but instead of applying the function to
values, it applies to the stopped signal. Therefore the function takes no arguments.

[source,cpp]
----
auto sndr = async::just_stopped();
auto us_sndr = async::upon_stopped(sndr, [] { return 42; });
// when run, us_sndr will produce 42 on the value channel
----

=== `when_all`

Found in the header: `async/when_all.hpp`

`when_all` takes a number of senders and after they all complete, forwards all
the values. If any of them produces an error or is cancelled, `when_all` cancels
the remaining senders.

Each sender passed to `when_all` must complete with `set_value` in exactly one way.

[source,cpp]
----
auto s1 = async::just(42);
auto s2 = async::just(17);
auto w = async::when_all(s1, s2);
// when w runs, s1 and s2 both run, and downstream receives both 42 and 17
----

NOTE: The order in which the sender arguments to `when_all` run is unspecified.

IMPORTANT: If _no_ arguments are given to `when_all`, it will complete
_immediately_. If only _one_ argument is given to `when_all`,
`when_all` has no effect. i.e. it behaves like the identity function.

=== `when_any`

Found in the header: `async/when_any.hpp`

`when_any` takes a number of senders and races them. It is available in
different flavors:

`when_any` determines completion as soon as any of its senders completes with
either `set_value` or `set_error`. It completes with the first such completion
it sees. If all its senders are complete with `set_stopped`, `when_any`
completes with `set_stopped`.

`first_successful` determines completion as soon as any of its senders completes
with `set_value`. It completes with the first such completion it sees. If no
senders complete with `set_value`, `first_successful` completes with the first
`set_error` completion it sees. If all its senders complete with `set_stopped`,
`first_successful` completes with `set_stopped`.

`stop_when` is a binary sender adaptor. It determines completion as soon as
either of its senders completes on any channel. Because it's a binary function,
`stop_when` can also be piped.

NOTE: As soon as a completion is determined, any remaining senders whose
completion becomes irrelevant are cancelled.

[source,cpp]
----
auto s1 = async::just(42);
auto s2 = async::just(17);
auto w = async::when_any(s1, s2);
// when w runs, s1 and s2 race; downstream receives either 42 or 17
----

[source,cpp]
----
auto s = some_sender | async::stop_when(some_other_sender);
// when s runs, some_sender and some_other_sender race
// the first to complete determines the completion of s
// the other is requested to stop
----

NOTE: For all flavors, the order in which the sender arguments run is
unspecified.

IMPORTANT: Each of these functions completes after all of its senders complete. The
completion reflects -- according to flavor -- which sender completed first, but
it cannot occur before all senders complete (regardless of the channel each may
complete on).

IMPORTANT: If _no_ arguments are given to `when_any`, it will _never_ complete
unless it is cancelled. If only _one_ argument is given to `when_any`,
`when_any` has no effect. i.e. it behaves like the identity function.
