
== Sender consumers

=== `start_detached`

`start_detached` takes a sender, connects and starts it, and returns, leaving
the work running detached. The return value is a
https://intel.github.io/cpp-std-extensions/#_optional_hpp[`stdx::optional`]. If
the optional is empty, the sender was not started. Otherwise, it contains a
pointer to an xref:cancellation.adoc#_cancellation[`inplace_stop_source`] that
can be used to cancel the operation.

[source,cpp]
----
auto sndr = async::just(42);
auto started = async::start_detached(sndr);
// in this case, starting the sender also completes it
----

If a sender starts detached, its operation state has to be allocated somewhere.
That is achieved through an xref:attributes.adoc#_allocator[allocator]
determined from the sender's attributes.

To hook into the static xref:attributes.adoc#_allocator[allocation strategy], a
template argument (representing the name of the allocation domain) can be given
to `start_detached`.

[source,cpp]
----
auto result = async::start_detached<struct Name>(s);
----

The default template argument results in a different `static_allocator` for each
call site, with a default allocation limit of 1. If the allocator's `construct` method
returns `false` (presumably because the allocation limit has been reached),
the result of `start_detached` is an empty optional.

=== `start_detached_unstoppable`

`start_detached_unstoppable` behaves identically to `start_detached`, except
that the returned optional value contains a pointer to a `never_stop_source`,
which has the same interface as an
xref:cancellation.adoc#_cancellation[`inplace_stop_source`] but never actually
cancels the operation. So `start_detached_unstoppable` is slightly more
efficient than `start_detached` for the cases where cancellation is not
required.

[source,cpp]
----
auto result = async::start_detached_unstoppable<struct Name>(s);
----

=== `sync_wait`

`sync_wait` takes a sender and:

. connects and starts it
. blocks waiting for it to complete
. returns any values it sends in a `std::optional<stdx::tuple<...>>`

[source,cpp]
----
auto sndr = async::just(42);
auto [i] = async::sync_wait(sndr).value();
// i is now 42
----
